<?php
//enquanto um dos 2 nao morrer disputar combate
while($_SESSION["forca"]>0&&$_GET["istamina"]>0)
{
$count++;$dice1=rand(1,6);$dice2=rand(1,6);$dice3=rand(1,6);$dice4=rand(1,6);
$resultado1=$dice1+$dice2+$_SESSION["pericia"];$resultado2=$dice3+$dice4+$_GET["iskill"];
if($_GET["pag"]=="6")
{
if($resultado1>$resultado2){if($_SESSION["item2"]=="warhammer"){$_GET["istamina"]-=4;$cqhits=0;echo "<h5>$count you hit your enemy with the Warhammer</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
elseif($_SESSION["item3"]=="silver_dagger"){$_GET["istamina"]-=3;$cqhits=0;echo "<h5>$count you hit your enemy with a silver dagger</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{$_GET["istamina"]-=2;$cqhits=0;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
else {$_SESSION["forca"]-=2;$cqhits++;$cdanos++;echo"<h5>$count You´ve been hit</h5><h5>Number of consecutive hits:$cqhits</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
if($cqhits==3){echo"<h5>You ´ve been hit three consecutive times go to page 18</h5>";break;}}
elseif($_GET["pag"]=="13"||$_GET["pag"]=="72")
{if($resultado1-2>$resultado2){if($_SESSION["item2"]=="warhammer"){$resultado1=$resultado1-2;$_GET["istamina"]-=4;echo "<h5>$count you hit your enemy with the Warhammer</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} -2 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{$resultado1=$resultado1-2;$_GET["istamina"]-=2;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} -2 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
else {$resultado1=$resultado1-2;$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} -2 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}}
elseif($_GET["pag"]=="20")
{if($_SESSION["item8"]=="silver_ring"){
if($resultado1+1>$resultado2){$resultado1=$resultado1+1;$_GET["istamina"]-=3;echo"<h5> $count You got the silver ring so Hit your enemy with extra damage</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} +1 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{
$roll=rand(1,6);if($roll==1||$roll==6){$resultado1=$resultado1+1;$_SESSION["forca"]-=4;$cdanos++;echo"<h5>$count You´ve been hit with 4 points of damage by the Gargoyle</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} +1 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-4;</script>";}
else{$resultado1=$resultado1+1;$_SESSION["forca"]-=3;$cdanos++;echo"<h5>$count You´ve been hit with 3 points of damage by the Gargoyle</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} +1 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-3;</script>";}
}}
else{
if($resultado1>$resultado2){$_GET["istamina"]-=2;$cdanos++;echo"<h5> $count You Hit your enemy </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{
$roll=rand(1,6);if($roll==1||$roll==6){$_SESSION["forca"]-=4;$cdanos++;echo"<h5>$count You´ve been hit with 4 points of damage by the Gargoyle</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-4;</script>";}
else{$_SESSION["forca"]-=3;$cdanos++;echo"<h5>$count You´ve been hit with 3 points of damage by the Gargoyle</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-3;</script>";}
}}}
elseif($_GET["pag"]=="30")
{if($resultado1>$resultado2){$_GET["istamina"]-=2;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else {if (rand(2,12)<$_SESSION["sorte"]){$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
else{$_SESSION["forca"]-=3;$cdanos++;echo"<h5>$count You´ve been hit with the demon battle axe</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-3;</script>";}}
}
elseif($_GET["pag"]=="38")
{if($resultado1>$resultado2){$_GET["istamina"]-=2;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else {$roll=rand(1,6);if($roll==1||$roll==3||$roll==5){$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
else{$_SESSION["forca"]-=3;$cdanos++;echo"<h5>$count You´ve been hit by the slime acid</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-3;</script>";}}
}
elseif($_GET["pag"]=="87")
{if($resultado1>$resultado2){if($_SESSION["item2"]=="warhammer"){$cqhits=0;$_GET["istamina"]-=4;echo "<h5>$count you hit your enemy with the Warhammer</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{$cqhits=0;$_GET["istamina"]-=2;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
else {$cqhits++;$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";
if($cqhits==3)
{$die=rand(1,6);if($die==6){$die2=rand(1,6);echo "<h5>You have been hit with special damage {$die2} </h5>"; 
if($die2==1){$_SESSION["forca"]-=1;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
elseif($die2==2){if (rand(2,12)>$_SESSION["pericia"]){echo "<h5>You are hit be his tail, but you are skillfull and regain your balance</h5>";}
else{$_SESSION["forca"]-=2;echo"<h5>$count You´ve been hit by his tail</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-1;</script>";}}
elseif($die2==3){$die3=rand(1,6);echo "<h5>The shadow Lord hit you with is horns you lose {$die3} Stamina points</h5>";$_SESSION["forca"]-=$die3;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-Number({$die3});</script>";}
elseif($die2==4){$_SESSION["forca"]-=2;echo"<h5>$count You´ve been hit by his tail spikes</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
elseif($die2==5){$_SESSION["sorte"]-=1;echo"<h5>$count the shadow lord cast a curse on you so you lose 1 luck point</h5>";echo "<script type='text/javascript'>sorte=Number(document.pontuacao.forca.value);document.pontuacao.sorte.value=sorte-1;</script>";}
elseif($die2==6){$_SESSION["forca"]-=2;echo"<h5>$count The shadow lord cast a spell You´ve been hit</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}}
}}}
elseif($_GET["pag"]=="91"||$_GET["pag"]=="122")
{if($_SESSION["item8"]=="silver_ring"){
if($resultado1+1>$resultado2){$resultado1=$resultado1+1;$_GET["istamina"]-=2;echo"<h5> $count You have got the silver ring and Hit your enemy </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} +1 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{
$resultado1=$resultado1+1;$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} +1 = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
}
else{if($resultado1>$resultado2){$_GET["istamina"]-=2;echo"<h5> $count You Hit your enemy </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
else{
$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You´ve been hit </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}}
if($count==3||$count==6||$count==9||$count==12||$count==15||$count==18||$count==21||$count==24)
{$roll=rand(1,6);if($roll<4){$_SESSION["forca"]-=2;echo"<h5>$count You´ve been cast a spell of weakning </h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}}
}
elseif($_GET["pag"]=="110")
{
	if ($resultado1> $resultado2 ) {if ($_SESSION["item2"]=="warhammer"){$_GET["istamina"]-=4;echo "<h5>{$count} you hit your enemy with the Warhammer</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
	elseif($_SESSION["item8"]=="silver_ring"){$_GET["istamina"]-=3;echo "<h5>{$count} you have the silver ring so you make one extra point of damage</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
	else{$_GET["istamina"]-=2;echo "<h5>{$count} you hit you enemy </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
	else{$roll=rand(1,6);if ($roll==1||$roll==6){$_SESSION["forca"]-=3;$cdanos++;echo "<h5>{$count} you roll {$roll} your oponnent did extra damage </h5>";}
	else {$_SESSION["forca"]-=2;$cdanos++; echo "<h5>{$count} You have been hit </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}}

elseif($_GET["pag"]=="143")
{ 
	if ($resultado1>$resultado2){if($_SESSION["item3"]=="silver_dagger"){$_GET["istamina"]-=4;echo"<h5>{$count} you hit your enemy with the silver dagger</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";
	$roll=rand(1,6);if($roll==1||$roll==3||$roll==5){$_GET["istamina"]-=1;echo"<h5>Grimbar hit the enemy</h5>";}}
	else{$_GET["istamina"]-=2;echo "<h5>{$count} you hit you enemy </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";
	$roll=rand(1,6);if($roll==1||$roll==3||$roll==5){$_GET["istamina"]-=1;echo"<h5>Grimbar hit the enemy</h5>";}}}
	else{echo"<h5>{$count}You have been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";$_SESSION["forca"]-=2;$cdanos++;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";$roll=rand(1,6);
	if ($roll==1||$roll==6){echo"<h5>You have been hit with extra damage</h5>";$_SESSION["forca"]-=1;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-1;</script>";}}}
elseif($_GET["pag"]=="159")
{
	if($resultado1<$resultado2){if($_SESSION["item8"]=="silver_ring"){$_GET["iskill"]=$_SESSION["iskill"];echo"<h5>{$count}You have been hit but have the silver ring</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";
	$_SESSION["forca"]-=1;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-1;</script>";}
	else{$_SESSION["forca"]-=2;$cdanos++;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";echo"<h5>{$count} You have been hit </h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}
	$roll=rand(1,6);$roll2=rand(1,6);if($roll==4||$roll==5||$roll==6){echo "<h5>You hit {$roll} and were able to beat the tentacle</h5>";}else{echo "<h5>You hit {$roll} and loose {$roll2} stamina points </h5>";
	$_SESSION["forca"]-=$roll2;echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-{$roll2};</script>";}}
	else{$_GET["istamina"]-=2;echo"<h5>{$count}You hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
elseif($_GET["pag"]=="160")
{if($resultado1<$resultado2){$roll=rand(1,6);if($roll==2||$roll==4||$roll==5){$_SESSION["forca"]-=2;$cdanos++;echo"<h5>{$count} You have been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";
echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}else{$_SESSION["forca"]-=3;$cdanos++;echo "<h5>{$count} You have been hit extra damage</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";
echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-3;</script>";}}else{$_GET["istamina"]-=2;echo "<h5>{$count} You hit the Wraith</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";}}
	
else{
	if($resultado1>$resultado2){$_GET["istamina"]-=2;echo "<h5>$count you hit your enemy</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";if($_SESSION["item10"]=="flame_sword"){$roll=rand(2,12);if($roll<$_SESSION["sorte"]){$roll2=rand(1,6);$_GET["istamina"]-=$roll2;
	echo"<h5>You hit your enemy with the flame sword</h5>";}}}

else {$_SESSION["forca"]-=2;$cdanos++;echo"<h5>$count You have been hit</h5><h5>You : <img src='../images/{$dice1}.jpg'> + <img src='../images/{$dice2}.jpg'> + {$_SESSION["pericia"]} = {$resultado1} Vs <img src='../images/{$dice3}.jpg'> + <img src='../images/{$dice4}.jpg'> + {$_GET["iskill"]} = {$resultado2}</h5>";echo "<script type='text/javascript'>forca=Number(document.pontuacao.forca.value);document.pontuacao.forca.value=forca-2;</script>";}
}
if ($_GET["istamina"]<=0){$_SESSION["nbattle"]+=1;echo"<h3>You Win!</h3>";}

}
	?>