<?php
echo"<div id='sayt'>";
		echo "<p>For many years, you have been a travelling adventurer, battling ferocious monsters like Orcs, Trolls and Wolves almost every single day. Your reputation has grown throughout this part of the land, and there are few who haven't heard of you. Ever since you were a child, you were trained in the art of swordplay by your now-deceased father. Since then, there have been none that could face you and survive.</p><br>";
echo "<p>Recently, you have come upon the village of Brookhaven. As you enter the village, you are rather surprised to see that most of the villagers give you unfriendly or fearful looks, and hurry to their homes. You decide to head for the village pub, a building with a sign overhanging it reading: 'The Twisted Blade Inn'. As soon as you enter the inn, you walk past the crowded tables and march straight towards the bar. The barkeeper, a large man with a short beard, looks up at you. Curiously, you ask him what is wrong with the villagers. In a grave voice, he relates to you a grim tale.</p><br>";
echo "<p>'A month ago, during a festival being held here in Brookhaven, we were attacked by a band of a dozen Orcs. They killed many of the villagers, looted the houses, and carried some of our men off as prisoners. At first we thought that it was a mere Orc raid, and from then on posted several guards at the edge of the village. Again they attacked a few days later, but this time they were driven out. Now, just a week and a half ago, the Orcs attacked again, but this time they were accompanied by powerful sorcerers who destroyed many of the buildings of the village with powerful fireballs. After this, we held a village meeting, and it was decided that the next time the Orcs attack, a spy should be sent after them. After the raid, which left two more villagers dead, a spy was indeed sent, and he followed them deep into the heart of that accursed wood, the Forest of Darkness! He saw them descend into a crypt beyond a trapdoor located in a clearing. We fear that there is some evil brewing in that crypt, and have tried to hire many warriors, but all have refused. I notice that you appear to be a fighter, so I beg you, please aid us!'</p><br>";
echo "<p>By this time, everyone in the inn is listening, and they all stare at you hopefully. After thinking it over, you announce your decision.</p>";
echo "<p>'People of Brookhaven, I shall journey through the Forest of Darkness and into the crypt. There, I shall wipe out the great evil that you fear so much. However, I won't do this job for free.'</p>";
echo "<p>The innkeeper chuckles, and tells you that should you succeed, a reward of 300 Gold Pieces, collected from the entire village, will be awaiting you. Hearing this, your jaw drops open in shock. The following morning, after packing all your belongings, you set out. You journey to the Forest of Darkness, and after trekking through it for several hours, as well as battling a pack of hungry wolves, stumble across the clearing. You see the trapdoor in the ground, and you tug at it with all your might. It creaks open slowly.<p>Now turn to section <a href=index2.php?pag=1>1</a>.</p>";
echo"</div>";
	?>