<?php
echo"<div id='sayt'>";
echo "<p>There is a poster on one of the walls on one of the taverns in Port Blacksand asking for adventurers to go straight to the palace, you decide to answer it. 
You are escorted to the gates of Lord Azzur’s palace. A palace guard opens the gate and allows you to step in. You are then brought through the courtyard. There is a structure in the centre with a worn rope hanging from it. You stare at it as you are rushed on through. The guard walks through the doorway of the palace and gestures for you to follow. The floor is made up of intricate fancy patterns and the walls are adorned with lapis lazuli, black granite and gold. You are taken into a very large room and at the far end of the place is a golden and silver throne, but no one is seated in it. ‘Kneel!’ Orders the guard and you get on one knee and lower your head. The wait is long but you dare not move from your position. Someone comes in to the room and you peak up just for a second to see who it is hoping it to be his Lordship but an old man in robes arrives. He is carrying a scroll and unravels it, ‘By the order of Lord Azzur you are prompted to go to Silhouette Island to collect the Sleeping Dragon. You shall take the Havica there. Upon your successful return, you will be rewarded, and his Lordship has requested your company for dinner. Do you accept this offering?’ You nod. ‘Good. Then take the funds for the brig’s captain and go straight to the harbour, there is no time to be wasted.’ He kicks a small chest in your direction. ‘Go now, and remember we are counting on you to survive. Inside the chest you will find an amulet, it is your only guarantee to get back into the palace, so put it on and wear it.’
</p>";
echo"<p>When you are leaving, you see a man hanging in the gallows outside. No one seems to care that he is hanging there dead except you. You wonder about this statue you are supposed to collect. You have many questions about it but doubt anyone will answer. Inside the chest are gold coins, you are sure you will be paid more than this when you are done. The amulet goes around your neck before the vagabonds here see you wearing it. </p>";
echo "<p>You hide the chest under your coat and walk swiftly to Harbour Street and there you find the Havica and board her. You give the captain the chest and he takes it happily. ‘So it is my duty to keep you alive, eh? Well, we shall see.’ He walks away leaving you standing there on the deck.</p>
<p>‘Land-ho!’ A seaman cries far up in the crow’s nest. Everyone cheers and watches over the starboard railing. You can see the hills of the island in the far distance and sigh that the first part of your journey is finally over. Just as things could not get better a long, slender tentacle comes out of the water. Everybody starts to panic and run about the place looking for anything to use as a weapon - tentacles larger than the first edge out, some now on the port side. They hug the ship and break the main mast. All you can hear is wood snapping and cracking. People are diving overboard or trying to fighting off the arms of the unseen beast. The deck breaks apart, and to your horror realise this creature means to destroy the ship. One man is grabbed from the deck, who holds on for dear life, and is squished in to two parts at the stomach by a tentacle. </p>
<p>You jump off the ship and swim as far as you can and stop to watch the Havica torn to bits by a monstrous squid. You must not stop though. You must continue swimming toward the island even though it is far. When you make it to the beach, you fall flat on your face and pass out…</p>
<p>‘Wake up…’ comes this voice. You open your eyes and see a guy smiling down at you. ‘You made it here safely all by yourself. The rest of us came in a boat. The Havica is gone, sunk beneath the waves.’ You get up and spot four men - the last survivors of the ship.</p>
<p>That night, they get a campfire going on the beach. To your right is a vast jungle. You know you must find the old temple within it. There is nothing to eat and all of you huddle there wondering what other terrors will arise. There is a loud shriek in the jungle and then commotion. Large white owl-like creatures burst from the trees and attack your party. You think you can fend them off with your sword but find more and more are emerging from the darkness. They are the size of a grown man with a wide wingspan. Your group is savagely attacked, their flesh torn to bits by talons. Blood splashes through the air and all that is heard by the fire are garbled screams and squawking birds. They do not attack you and rather than stick around you run as hard as you can through the trees. You do not know how long you have been running for but you just cannot run any further. You climb up a tree and rest there.</p>
<p>Turn to <a href='index2.php?pag=1'>1</a> .</p></div>";
?>
