-- phpMyAdmin SQL Dump
-- version 3.3.8.1
-- http://www.phpmyadmin.net
--
-- Máquina: localhost
-- Data de Criação: 27-Jan-2011 às 12:29
-- Versão do servidor: 5.0.91
-- versão do PHP: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de Dados: `ffgamebo_books`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `thebeast`
--

CREATE TABLE IF NOT EXISTS `thebeast` (
  `incremento` int(11) NOT NULL auto_increment,
  `textos` text,
  `inimigos` varchar(40) default NULL,
  `pericia` int(2) default NULL,
  `forca` int(2) default NULL,
  `imagem` varchar(30) default NULL,
  PRIMARY KEY  (`incremento`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=42 ;

--
-- Extraindo dados da tabela `thebeast`
--

INSERT INTO `thebeast` (`incremento`, `textos`, `inimigos`, `pericia`, `forca`, `imagem`) VALUES
(1, 'Gathering your possessions (record a Torch, Knife, 5 Provisions and 30 Gold Pieces on your Adventure Sheet), you head out at first light, hoping that the Beast will not be up and roaming so early. The villagers watch you leave with heavy hearts for their fates depend on you. Soon both they and the village become a mere speck in the distance. You cut through the corn fields rejoining the road path that forks ahead. The northern trail leads into the woods, whilst the trail northwest will take you on a more direct route across the moors. If you are the Farmer, turn to <a href=index2.php?pag=25>25</a>. If not, do you travel north (turn to <a href=index2.php?pag=29>29</a>) or northwest (turn to <a href=index2.php?pag=11>11</a>)?', '', 0, 0, ''),
(2, 'You endure one of the most frightful hours of your life in the cave. You keep still in the darkness afraid to make even the slightest noise. The Beast wanders here and there, seemingly knowing that there is someone about. It passes the cave twice hissing and growling. Thankfully, it soon tires of the search and moves elsewhere leaving you in silence. You dare not sleep for fear that it should return to look for you. Lose 1 Luck point. With the approach of dawn, you pluck up the courage to check the surroundings before exiting the cave. The valley begins to widen and you leave the river behind to follow what looks a wagon trail going over the hills. You scale it without too much difficulty and standing at its peak, you are relieved to see a town within walking distance. To enter, turn to <a href=index2.php?pag=9>9</a>.', '', 0, 0, 'imagens/cave3.png'),
(3, 'Your heart leaps when your saviour returns with evidence of the Beast?s demise and you offer your thanks over and over. Add 1 Luck point. Now you must journey back to your village to spread the news. Will you take the path across the moors (turn to <a href=index2.php?pag=39>39</a>) or through the woods (turn to <a href=index2.php?pag=16>16</a>)?', '', 0, 0, ''),
(4, 'A tentacle coils around your leg but you slash it off with your knife and stab at its underbelly. The creature?s hide seems to be comprised of solid earth and your knife breaks from the impact. If you don?t have another weapon you must reduce your Attack Strength by 1 in combat until you find a replacement. The Beast slams into you knocking you to the ground (lose 1 Stamina point). Will you flee now that you have lost your knife (turn to <a href=index2.php?pag=7>7</a>) or are you still keen on making a stand (turn to <a href=index2.php?pag=37>37</a>)?', '', 0, 0, 'imagens/tentacle.png'),
(5, 'Unwittingly you have chosen to rest in an area that is part of an animal?s territory. It catches your scent and you must defend yourself with your knife as it charges at you.\r\n\r\nWILD ANIMAL     SKILL   6     STAMINA   5\r\n\r\nYou cannot Escape. If you win, turn to the paragraph number you noted earlier.\r\n', 'WILD ANIMAL', 6, 5, 'imagens/wild_pig.jpg'),
(6, 'The hills at the end of the valley look familiar ? you must be nearing your village. You make haste towards them but a figure blocks your path. He demands that you give him 5 Gold Pieces or he will run you through?then take your gold anyway. If you can and wish to give the bandit 5 Gold Pieces, he will let you pass. Turn to <a href=index2.php?pag=35>35</a>. Otherwise, he engages you in combat.\r\n\r\nBANDIT     SKILL   7     STAMINA   6\r\n\r\nIf you are triumphant, turn to <a href=index2.php?pag=35>35</a>. If he kills you, at least you can take comfort in the fact that your village will be safe. But you will not see it again. Your adventure ends so near and yet so far from home.\r\n', 'BANDIT', 7, 6, 'imagens/bandit.png'),
(7, 'You flee into the night. The Beast pursues you but soon gives up. You keep running until your legs tire and you pause for breath. You may eat provisions here as you rest and wait for dawn. If you are the Herbalist, you discover a plant in the undergrowth that you recognise for its healing properties. You may use it to restore any Skill points you may have lost. If you are the Blacksmith and have lost your knife, you need not make any deductions to your Attack Strength in combat since your strength is as effective as any weapon. If you are the Farmer, you dig up a few edible tubers. It?s hardly a banquet but they are nourishing and you may restore 2 points of Stamina. Did you come through the woods (turn to <a href=index2.php?pag=40>40</a>) or did you cross the moors into a valley (turn to <a href=index2.php?pag=8>8</a>)?', '', 0, 0, ''),
(8, 'You carry on through the valley which begins to widen and you leave the river behind to follow what looks a wagon trail going over the hills. You scale it without too much difficulty and, standing at its peak, you are relieved to see a town within walking distance. To enter, turn to <a href=index2.php?pag=9>9</a>.', '', 0, 0, 'imagens/vila.jpg'),
(9, 'While you are in town, you can buy a knife for 3 Gold Pieces and provisions at 1 Gold Piece per meal. Your desperate pleas for aid attract the attention of several would-be heroes. Quickly, you relate the dire situation to them. The Warrior is the most expensive at 20 Gold Pieces. The Sorceress can be hired for 15 Gold Pieces, and lastly, the Knight asks only for 5. Decide on who you wish to hire and deduct the appropriate amount of Gold from your Adventure Sheet. Whose services have you bought?\r\n\r\nWarrior. Turn to <a href=index2.php?pag=12>12</a>.\r\nSorceress. Turn to <a href=index2.php?pag=33>33</a>.\r\nKnight. Turn to <a href=index2.php?pag=26>26</a>.\r\n\r\nIf you can no longer afford anyone or if there is no one left to help, turn to <a href=index2.php?pag=34>34</a>.\r\n', '', 0, 0, 'imagens/vila3.gif'),
(10, 'Your aid comes back to town looking worse for wear and moans bitterly at you. ?That foul monster was far larger than you described. I barely escaped with my life. If you want me to face that thing again, it?ll cost you another 5 Gold Pieces.? As you consider this demand, your aid quaffs a potion and recovers 4 Stamina points. If you can afford the price and want to pay up, you do so. Return to <a href=index2.php?pag=20>20</a> and finish the fight ? this time to the death. If you reconsider, you call for one of the other heroes. Return to <a href=index2.php?pag=9>9</a> and choose someone else.', '', 0, 0, ''),
(11, 'Open country is always more dangerous. There are many hills and rough terrain about and progress is often hard. By noon you have left the trail for more even ground and come into a valley where a river flows. You should be able to reach your destination by following it. You must rest a while and eat a meal. Make a note of the number 30 on your Adventure Sheet and roll one die. If you roll a 1 or 2, turn to <a href=index2.php?pag=36>36</a>. If you roll a 3 or 4, turn to <a href=index2.php?pag=5>5</a>. If you roll a 5, turn to <a href=index2.php?pag=27>27</a>. If you roll a 6, turn to <a href=index2.php?pag=18>18</a>.', '', 0, 0, 'imagens/catarata.gif'),
(12, 'The Warrior wears a simple tunic and carries a large axe. He assures you that his skill is such that he has yet to face a worthy opponent. He looks every bit as tough as he claims. These are his attributes:\r\n\r\nSKILL   12\r\nSTAMINA   15\r\nLUCK   7\r\n\r\nYou tell him where you last encountered the Beast and he tells you to stay put and await the news of his victory. For the next paragraph only, you must take control of the Warrior?s actions. Turn to <a href=index2.php?pag=20>20</a>.\r\n', '', 0, 0, 'imagens/ax.gif'),
(13, 'This is folly. The Beast is far too powerful for you to handle and any strike you eventually land is futile against its tough hide. You must try to escape its clutches but it costs you a total of 4 Stamina points and 1 Skill point. If you are still alive after the battering, turn to <a href=index2.php?pag=7>7</a>.', '', 0, 0, ''),
(14, 'You approach the trees in front of you. There is plenty of cover and your flame dispels a little of the surrounding darkness, but you feel very vulnerable all the time. Twigs snap and leaves crunch nearby. Terror grips you and you draw your knife crouching behind a large oak. Silence descends. You can?t see anything out there. Just as you are beginning to question whether it was the Beast after all, the ground beside you heaves and a great barrel of a creature bursts out from the earth itself. You scream and fall backwards as it takes a ponderous step towards you. Your light illuminates a toothy maw and those nightmarish eyes. It towers over you shaking off mud, roots and gravel to reveal numerous arms and tentacles. It roars and makes a grab for you. Will you strike with your knife (turn to <a href=index2.php?pag=4>4</a>) or make a run for it (turn to <a href=index2.php?pag=7>7</a>)?', '', 0, 0, ''),
(15, 'The valley begins to widen and you leave the river behind to follow what looks a wagon trail going over the hills. You scale it without too much difficulty and, standing at its peak, you are relieved to see a town illuminated by streetlamps within walking distance. Suddenly, the sound of snapping branches and rustling leaves makes you turn to see a tree toppling. A huge silhouette rises from the earth itself and you know it is the Beast. A terrible roar rends the air and you flee in panic towards the town before the light of your torch fails. Night has fallen so now is probably not the best time to go looking for help. You decide to rest at an inn until morning. A room costs 2 Gold Pieces and it is another 2 for cooked food. If you take the room only, you can restore 2 points of Stamina and you must eat one of your own provisions. If you pay for food as well, you can restore up to 4 points of Stamina. You enjoy a good night?s sleep and get back to the task at hand early the next day. Turn to <a href=index2.php?pag=9>9</a>.', '', 0, 0, 'imagens/vila2.gif'),
(16, 'Thrilled at your success, you journey hastily through the woods stopping only to catch breath. Progress slows when the trees become more tightly packed and soon you have to pause for a short break. You must eat a meal. You have not gone far when a couple of impish humanoids burst out of the foliage sneering at you. They carry shortswords and their intentions are far from friendly. You must fight them together.\r\n\r\nGOBLIN     SKILL   5     STAMINA   5\r\nGOBLIN     SKILL   5     STAMINA   4\r\n\r\nIf you win, turn to <a href=index2.php?pag=35>35</a>. If they kill you, at least you can take comfort in the fact that your village will be safe. But you will not see it again. Your adventure ends so near and yet so far from home. \r\n', 'GOBLIN', 5, 5, 'imagens/goblins.gif'),
(17, 'If you choose the Herbalist, you will be able to recognise and gather many types of herbs and plants that grow in the area. These you can use to counter poisons, heal wounds and deter certain animals.\r\n\r\nIf you choose the Farmer, you will know a little more about the countryside around your village having worked in the fields for most of your life. You are quite capable in cultivating plants and vegetables for the best results.\r\n\r\nIf you choose the Blacksmith, most of your time will be spent hammering away in the forge producing objects of iron and repairing metalwork. Years of practice have developed your strength and you may add 2 to both your current and Initial Stamina scores. \r\n\r\nWhen you have decided on your character, turn to <a href=index2.php?pag=1>1</a>.\r\n', '', 0, 0, ''),
(18, 'You spot a corpse lying amongst some bushes nearby. On closer inspection you see that it is a young adventurer who has suffered many grievous wounds. His killer, however, has overlooked a box that has rolled out of his torn backpack into the long grass. The box is locked. Only if you are the Blacksmith do you succeed in opening it and are delighted to find a Potion of Strength inside which will restore your Stamina to its Initial level. You can drink it at any time except during combat. If you are not the Blacksmith, it stays stubbornly shut and you discard it in frustration. Turn to the paragraph number you noted earlier.', '', 0, 0, ''),
(19, 'You find two daggers, a total of 8 Gold Pieces between them and a snake branded on their wrists. It looks like a bandit mark so there may be more of their fellows out there. You hide the bodies before leaving. Turn to the paragraph number you noted earlier.', '', 0, 0, ''),
(20, 'The hysterical villager claimed that the Beast was somewhere between the woods and the valley hills. You expect a large creature to be easy to track but there doesn?t appear to be any sign of its whereabouts. Soon you come to an area of fallen trees and crushed vegetation. It is likely the Beast came this way recently. Then you notice a huge shadow looming behind you and just manage to evade it as a great mound of roots and dripping soil descends upon you. It growls with hate and reaches out with a misshapen arm to crush the life out of you. You must fight.\r\n\r\nTHE BEAST     SKILL   12     STAMINA   15\r\n\r\nIf the Beast has fought earlier, amend its scores accordingly. Any damage you inflict on the creature is reduced by 1 point due to its tough hide. If you are the Sorceress, you can fling Fireballs at the Beast causing it to lose 2 points of Stamina and 1 point of Skill with each Attack Round you win. (You can increase the damage to 4 points of Stamina and 1 point of Skill if you successfully Test your Luck, but no damage is caused if you fail.) You can Escape back to town at any time if you succeed in hitting it at least twice. You cannot do this if you are the Knight. If you kill it, turn to <a href=index2.php?pag=3>3</a>. If not, make a note of its scores. If you flee back into town, turn to <a href=index2.php?pag=10>10</a>. If you are slain by the Beast, turn to <a href=index2.php?pag=38>38</a>.\r\n', '', 0, 0, 'imagens/beast.gif'),
(21, 'A quick search downstairs proves fruitless so you climb the ladder to the top floor. Here you discover your Gold Brooch ? a family heirloom that you stashed here for safekeeping and had all but forgotten about. It is worth 5 Gold Pieces. You peer out of the window to see a canopy of leaves ahead. There appears to be a large area of space towards the eastern edge presumably made by the Beast that attacked your village. Next to the woods are hills leading into a valley where a river runs through. Leaving the mill, do you want to travel north (turn to <a href=index2.php?pag=29>29</a>) or northwest (turn to <a href=index2.php?pag=11>11</a>)?', '', 0, 0, ''),
(22, 'Fortunately the cave is abandoned and you settle down for the night. You must eat a meal. The temperature drops and you gather some dry grass to build a small fire by the entrance. You have slept for only a few hours when a terrible roar rends the air. You jump to your feet at once. Thunderous footsteps shake the earth and trees topple down the hill. The Beast is close! Do you want to grab your torch and go out to investigate (turn to <a href=index2.php?pag=14>14</a>) or smother the fire and hide in the cave (turn to <a href=index2.php?pag=2>2</a>)?', '', 0, 0, ''),
(23, 'You carry on through the woods without encountering any obstruction. The trees begin to spread further and further apart until you see only grassland ahead and hills to your left. There is a well-used footpath here leading into a field and you follow it. You are relieved to see a town not far away. Suddenly, the sound of snapping branches and rustling leaves makes you turn to see a tree toppling. A huge silhouette rises from the earth itself and you know it is the Beast. A terrible roar rends the air and you flee in panic towards the town before the light of your torch fails. Night has fallen so now is probably not the best time to go looking for help. You decide to rest at an inn until morning. A room costs 2 Gold Pieces and it is another 2 for cooked food. If you take the room only, you can restore 3 points of Stamina and you must eat one of your own provisions. If you pay for food as well, you can restore up to 5 points of Stamina. You enjoy a good night?s sleep and get back to the task at hand early the next day. Turn to <a href=index2.php?pag=9>9</a>.', '', 0, 0, 'imagens/vila2.gif'),
(24, 'Test your Luck. If you are Lucky, turn to <a href=index2.php?pag=7>7</a>. If you are Unlucky, you stumble and lose your way in the darkness. Since you don?t have a light source, you have no idea that you are in fact going in the wrong direction. As you contemplate where to go, a giant creature bursts forth from the ground, seizing you with a soil-covered limb. There is nothing you can do to stop the Beast from squeezing the life out of you. Your adventure ends here.', '', 0, 0, ''),
(25, 'Not far away is the Old Mill which you visit now and again. There may be something left inside that could be of use to you. Will you make a search of the place first (turn to <a href=index2.php?pag=21>21</a>) or, will you take the road north (turn to <a href=index2.php?pag=29>29</a>) or northwest (turn to <a href=index2.php?pag=11>11</a>) immediately?', '', 0, 0, 'imagens/mill.gif'),
(26, 'The Knight is dressed in chainmail and wields a broadsword. He fights not for money but to rid the world of such beasts of destruction. The gold will be donated to his temple of worship. These are his attributes:\r\n\r\nSKILL   10\r\nSTAMINA   18\r\nLUCK   8\r\n\r\nYou tell him where you last encountered the Beast and he tells you to stay put and await the news of his victory. He will not return until the deed is done. For the next paragraph only, you must take control of the Knight?s actions. Turn to <a href=index2.php?pag=20>20</a>.\r\n', '', 0, 0, 'imagens/knight.gif'),
(27, 'There are trees growing here with strangely shaped purple fruits. If you are the Herbalist, you recognise them as highly nutritious if rather bitter-tasting. You collect enough for two meals. If you are the Farmer or Blacksmith, you leave them alone after taking a bite. Turn to the paragraph number you noted earlier.', '', 0, 0, ''),
(28, 'The Beast seizes you in a vice-like grip and pulls you close to watch you squirm in pain (lose 2 Stamina points). In desperation, you thrust your torch forwards burning its face. The creature roars and throws you aside. A bush breaks your fall but the torch is extinguished. As the Beast clutches its scorched face you make good your escape. Make a note that if the Beast engages in combat later, its Skill and Stamina will be reduced by 1 point. Add 1 Luck point for your minor victory and turn to <a href=index2.php?pag=7>7</a>.', '', 0, 0, ''),
(29, 'The trail disappears into the undergrowth and the trees become more densely packed. You keep to the western edge of the woods where there is more light. The detour provides you with some much needed cover but the going is slower than if you had taken the trail across the moors. The trees begin to thin out by high noon and you rest in a clearing to catch your breath. You must eat two meals. Make a note of the number 32 on your Adventure Sheet and roll one die. If you roll a 1, turn to <a href=index2.php?pag=36>36</a>. If you roll a 2 or 3, turn to <a href=index2.php?pag=5>5</a>. If you roll a 4 or 5, turn to <a href=index2.php?pag=27>27</a>. If you roll a 6, turn to <a href=index2.php?pag=18>18</a>.', '', 0, 0, ''),
(30, 'You continue through the valley for a few more hours without incident. It is getting dark and you light your torch for better visibility. You could soldier on through the evening if you wanted to ? the town can?t be too much further ahead. Turn to <a href=index2.php?pag=15>15</a>. Alternatively, there is a convenient cave at the top of a hill if you want to shelter there for the night. Turn to <a href=index2.php?pag=22>22</a>.', '', 0, 0, ''),
(31, 'You must eat a meal. The temperature drops and you build a fire before settling down for the night. You have slept for only a few hours when a terrible roar rends the air. You jump to your feet at once. Thunderous footsteps shake the earth and trees topple nearby. The Beast is close! Do you want to grab your torch and investigate (turn to <a href=index2.php?pag=14>14</a>) or smother the fire and creep away (turn to <a href=index2.php?pag=24>24</a>)?', '', 0, 0, ''),
(32, 'You continue through the woods for a few more hours without incident. It is getting dark and you light your torch for better visibility. You could soldier on through the evening if you wanted to ? the town can?t be too much further ahead. Turn to <a href=index2.php?pag=23>23</a>. Otherwise, you will have to camp in a clearing. Turn to <a href=index2.php?pag=31>31</a>.', '', 0, 0, 'imagens/woods.gif'),
(33, 'The Sorceress wears flowing robes of brilliant yellow and crimson. She is well versed in magical arts and tells you that the ravening monster should not pose a problem. These are her attributes:\r\n\r\nSKILL   9\r\nSTAMINA   12\r\nLUCK   10\r\n\r\nYou tell her where you last encountered the Beast and she tells you to stay put and await the news of her victory. For the next paragraph only, you must take control of the Sorceress? actions. Turn to <a href=index2.php?pag=20>20</a>.\r\n', '', 0, 0, 'imagens/sorceress.gif'),
(34, 'Your attempts to rid the Beast have been in vain. Without money, your voice falls on deaf ears. Sullenly, you journey back to your village. But you return only to witness devastation: homes lie in ruins, crops completely destroyed, and many of your people have been killed trying to defend it. Tears well in your eyes and you collapse on to your knees. You have failed them.', '', 0, 0, ''),
(35, 'At last, your village comes into view and you wave your arms with joy to the people in the distance. Immediately they realise your success and greet you with open arms and a hero?s welcome. That night a celebration is held. You tell your tale to the villagers around a campfire and then you are presented with a medal of bravery by the village elders. A plaque is carved in your name to be remembered for scores of years and you are even put into a minstrel?s song. But for you, the greatest reward is simply that your dear village and its people are safe once more?and that is all that shall ever matter.', '', 0, 0, ''),
(36, 'You are surprised by a pair of bandits lurking in the shadows. They come at you together and you must defend yourself with your knife.\r\n\r\nBANDIT     SKILL   7     STAMINA   5\r\nBANDIT     SKILL   6     STAMINA   6\r\n\r\nYou may Escape after two rounds of combat ? turn to the paragraph number you noted earlier. If you manage to kill them both, turn to <a href=index2.php?pag=19>19</a>.\r\n', 'BANDIT', 7, 5, 'imagens/bandit.png'),
(37, 'Test your Luck. If you are Lucky, turn to <a href=index2.php?pag=28>28</a>. If you are Unlucky, turn to <a href=index2.php?pag=13>13</a>.', '', 0, 0, ''),
(38, 'You wait for hours but your aid does not return. You must call for one of the other willing heroes. Go back to <a href=index2.php?pag=9>9</a> and choose someone else.', '', 0, 0, ''),
(39, 'Thrilled at your success, you journey hastily over the hills until you come into a valley where a river flows. You should be able to reach your destination by following it south. You travel light, pausing only to catch breath. Test your Skill. If you are successful, you spot a concealed trap and skirt around it. Turn to 6. If you are unsuccessful, you fall into a stake-filled pit! The fall is not fatal but you must deduct 3 Stamina points and 1 Skill point for your injuries. Painfully, you climb out tearing strips from your shirt to make bandages. If you are the Herbalist, you collect some curative shrubs in the area, crush them and apply it to your wounds. You may restore the lost Skill point. Turn to <a href=index2.php?pag=6>6</a>.', '', 0, 0, 'imagens/catarata.gif'),
(40, 'You carry on through the woods without encountering any obstruction. The trees begin to spread further and further apart until you see only grassland ahead and hills to your left. There is a well-used footpath here leading into a field and you follow it. You are relieved to see a town not far away and you enter. Turn to <a href=index2.php?pag=9>9</a>.', '', 0, 0, 'imagens/planicie.jpg');
