<?php
//historia percorrida
if($_GET["pag"]=="1")
{$_SESSION["history"].="1,";}
elseif($_GET["pag"]=="2")
{$_SESSION["history"].="2,";}
elseif($_GET["pag"]=="3")
{$_SESSION["history"].="3,";}
elseif($_GET["pag"]=="4")
{$_SESSION["history"].="4,";}
elseif($_GET["pag"]=="5")
{$_SESSION["history"].="5,";}
elseif($_GET["pag"]=="6")
{$_SESSION["history"].="6,";}
elseif($_GET["pag"]=="7")
{$_SESSION["history"].="7,";}
elseif($_GET["pag"]=="8")
{$_SESSION["history"].="8,";}
elseif($_GET["pag"]=="9")
{$_SESSION["history"].="9,";}
elseif($_GET["pag"]=="10")
{$_SESSION["history"].="10,";}
elseif($_GET["pag"]=="11")
{$_SESSION["history"].="11,";}
elseif($_GET["pag"]=="12")
{$_SESSION["history"].="12,";}
elseif($_GET["pag"]=="13")
{$_SESSION["history"].="13,";}
elseif($_GET["pag"]=="14")
{$_SESSION["history"].="14,";}
elseif($_GET["pag"]=="15")
{$_SESSION["history"].="15,";}
elseif($_GET["pag"]=="16")
{$_SESSION["history"].="16,";}
elseif($_GET["pag"]=="17")
{$_SESSION["history"].="17,";}
elseif($_GET["pag"]=="18")
{$_SESSION["history"].="18,";}
elseif($_GET["pag"]=="19")
{$_SESSION["history"].="19,";}
elseif($_GET["pag"]=="20")
{$_SESSION["history"].="20,";}
if($_GET["pag"]=="21")
{$_SESSION["history"].="21,";}
elseif($_GET["pag"]=="22")
{$_SESSION["history"].="22,";}
elseif($_GET["pag"]=="23")
{$_SESSION["history"].="23,";}
elseif($_GET["pag"]=="24")
{$_SESSION["history"].="24,";}
elseif($_GET["pag"]=="25")
{$_SESSION["history"].="25,";}
elseif($_GET["pag"]=="26")
{$_SESSION["history"].="26,";}
elseif($_GET["pag"]=="27")
{$_SESSION["history"].="27,";}
elseif($_GET["pag"]=="28")
{$_SESSION["history"].="28,";}
elseif($_GET["pag"]=="29")
{$_SESSION["history"].="29,";}
elseif($_GET["pag"]=="30")
{$_SESSION["history"].="30,";}
elseif($_GET["pag"]=="31")
{$_SESSION["history"].="31,";}
elseif($_GET["pag"]=="32")
{$_SESSION["history"].="32,";}
elseif($_GET["pag"]=="33")
{$_SESSION["history"].="33,";}
elseif($_GET["pag"]=="34")
{$_SESSION["history"].="34,";}
elseif($_GET["pag"]=="35")
{$_SESSION["history"].="35,";}
elseif($_GET["pag"]=="36")
{$_SESSION["history"].="36,";}
elseif($_GET["pag"]=="37")
{$_SESSION["history"].="37,";}
elseif($_GET["pag"]=="38")
{$_SESSION["history"].="38,";}
elseif($_GET["pag"]=="39")
{$_SESSION["history"].="39,";}
elseif($_GET["pag"]=="40")
{$_SESSION["history"].="40,";}
?>